version: '3'

services:
  nlweb:
    build: .
    container_name: neslter
    volumes:
      - ./data:/data
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/certs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nlweb
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
