version: '3'

services:
  neslter:
    build: .
    container_name: neslter
    environment:
      - DATA_ROOT=/data
    volumes:
      - ${DATA_ROOT}:/data
      - ${LOCAL_SETTINGS}:/neslter/nlweb/nlweb/local_settings.py
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - NGINX_HOST=${HOST}
      - NGINX_HTTP_PORT=${HTTP_PORT}
      - NGINX_HTTPS_PORT=${HTTPS_PORT}
    volumes:
      - ./nginx_templates:/etc/nginx/templates
#      - ${NGINX_LOG_DIR}:/var/log/nginx
      - ./nginx_logs:/var/log/nginx
      - ${SSL_KEY}:/ssl/ssl.key:ro
      - ${SSL_CERT}:/ssl/ssl.cer:ro
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${HTTPS_PORT}:${HTTPS_PORT}
    depends_on:
      - neslter
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge