version: '3'

services:
  nlweb:
    build: .
    container_name: neslter
    volumes:
      - /data:/data
      - ./neslter:/neslter/neslter
      - ./nlweb:/neslter/nlweb
    networks:
      - nginx_network
      - postgres_network
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certs:/etc/certs
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nlweb
    networks:
      - nginx_network

  postgres:
    image: mdillon/postgis:11-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=neslter
      - POSTGRES_PASSWORD=neslter
      - POSTGRES_DB=neslter
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - postgres_network

networks:
  nginx_network:
    driver: bridge
  postgres_network:
    driver: bridge
